services:
  - type: web
    name: gix-gadgets-backend
    runtime: node
    buildCommand: "cd Backend && npm install"
    startCommand: "cd Backend && node index.js"
    envVars:
      - key: PORT
        value: 5555
      - key: MONGO_URL
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://level-3-project-three.vercel.app,http://localhost:5173,http://localhost:5174"

databases:
  - name: mongodb
    databaseName: gadgets-db
    plan: free
